export const UPLOAD_CURRENCIES = "UPLOAD_CURRENCIES";

export const UPDATE_DATE_INTERVAL = "UPDATE_DATE_INTERVAL";
export const UPDATE_DATE_INTERVAL_SUCCESS = "UPDATE_DATE_INTERVAL_SUCCESS";
export const UPDATE_DATE_INTERVAL_FAILURE = "UPDATE_DATE_INTERVAL_FAILURE";

export const ADD_REQUEST_CURRENCY = "ADD_REQUEST_CURRENCY";
export const REMOVE_REQUEST_CURRENCY = "REMOVE_REQUEST_CURRENCY";